version: '3'
services:

  dsw-server:
    image: {SERVER_IMAGE}
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./dsw.yml:/application/engine-wizard/config/application.yml:ro
    depends_on:
      - minio
      - postgres

  postgres:
    image: postgres:13.7
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dsw

  minio:
    image: minio/minio:RELEASE.2021-03-17T02-33-02Z
    command: server /data
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioPassword
